### ISSUE TITLE
http:// invalid hostname

### ISSUE THREAD

**Issue by sahinyanlik** [aitap/scripts#1] opened 2013-12-11 16:12 UTC
It says http://invalid hostname 

good day

**Comment by aitap** [comment] 2013-12-11 16:16
Hi! Which one of the scripts says this?

By the way, some of them are unused, unmaintained and broken.

**Comment by sahinyanlik** [comment] 2013-12-11 16:18
Ok I am using yandex-download script. I give the link but it says http://invalid hostname. That would be good to download from yandex link for example like this : https://disk.yandex.com.tr/public/?hash=rMEyhgapVkf0vMpWAiCqweyPUULAQtcqCAEE6cPsgQ4%3D

**Comment by aitap** [comment] 2013-12-11 16:58
> https://disk.yandex.com.tr/public/?hash=rMEyhgapVkf0vMpWAiCqweyPUULAQtcqCAEE6cPsgQ4%3D

This script is not going to work. yandex-downloader was intended to work
with "Narod.disk" web file hosting which has been suppressed by
Yandex.Disk cloud file hosting. And even when it worked, it was powered
by some rule of thumb black magic which I didn't completely understand.

However, I was able to dig through their javascript and create a new
script to download from Yandex.Disk. Try the newly uploaded
'yandexdisk.pl' for yourself, it looks like it's working.

**Comment by aitap** [comment] 2016-07-12 20:23
Closing because JS-filled clouds have won and I'm removing the script altogether

**Closed as completed by aitap** 2016-07-12 20:23 UTC
